name: Rust

on:
  push:
    branches: ["main", "dev-rust-port"]
  pull_request:
    branches: ["main", "dev-rust-port", "*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Rustfmt
        run: cargo fmt --all

      - name: Test
        run: cargo test

  test-no_std:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Test
        run: cargo test --features no_std

  test-legacy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Test
        run: cargo test --features legacy
